<h3>Mis Manuscritos</h3>

<div class="table-responsive">
  <table class="table table-bordered">
      
      
      <thead>
        <th>Nro</th>
        <th>T&iacute;tulo</th>
      </thead>
      
      <tbody>
          
          <?php for($i = 0; $i < count($this->manuscritos); $i++): ?>
          
          <tr>
              <td><?php echo $this->manuscritos[$i]['id_manuscrito']; ?></td>
              <td><a href="<?php echo BASE_URL . 'manuscrito/misManuscritos/'. $this->pagina.'/'. $this->manuscritos[$i]['id_manuscrito'];?>"><?php echo $this->manuscritos[$i]['titulo']; ?></a></td>
          </tr>
          
          <?php endfor; ?>
          
      </tbody>
      
  </table>
    
</div>


<ul class="pagination">
    <?php if(isset($this->paginacion)) echo $this->paginacion;?>
</ul>




